name: Demo Gold Image Pipeline for NGINX

on:
  push:
    branches:
      - main

jobs:
  gold-image:
    name: Gold Image Pipeline
    runs-on: ubuntu-20.04
    env:
      CHEF_LICENSE: accept
      PROFILE: my_nginx
    steps:
      - name: Update ubuntu
        run: sudo apt-get update -y

      - name: PREP - Install InSpec executable
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 5

      - name: PREP - Install SAF CLI
        run: npm install -g @mitre/saf

      # - name: CHECK - ls
      #   run: ls -l

      # - name: CHECK - pwd
      #   run: pwd

      # - name: CHECK - Parent directory ls
      #   run: cd ..; ls -l

      - name: PREP - Check out this repository
        uses: actions/checkout@v3

      # double-check that we don't have any serious issues in our profile code
      - name: LINT - Run InSpec Check
        run: inspec check $PROFILE

      # launch a container as the test target
      - name: DEPLOY - Run a Docker container from nginx
        run: docker run -dit --name nginx nginx:latest

      # install dependencies on the container so that hardening will work
      - name: DEPLOY - Install Python for our nginx container
        run: |
          docker exec nginx apt-get update -y
          docker exec nginx apt-get install -y python3
